plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'com.google.gms.google-services'
    id 'com.batodev.releasetools'
    id 'io.gitlab.arturbosch.detekt'
}

def keystorePropertiesFile = rootProject.file("../keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def versionProps = new Properties()
file("version.properties").withInputStream { versionProps.load(it) }

android {
    defaultConfig {
        applicationId "com.batodev.jigsawpuzzlecuties"
        minSdkVersion 24
        compileSdk = 37
        targetSdkVersion 37
        versionCode versionProps.getProperty("versionCode").toInteger()
        versionName versionProps.getProperty("versionName")
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile rootProject.file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    namespace 'com.batodev.jigsawpuzzlecuties'

    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.exifinterface
    implementation libs.chrisbanes.photoview
    implementation libs.play.services.ads
    implementation libs.androidx.multidex
    implementation libs.bumptech.glide
    implementation libs.caverock.androidsvg.aar
    implementation libs.google.play.review.ktx
    implementation libs.otaliastudios.zoomlayout
    implementation libs.google.code.gson
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.analytics
    ksp libs.bumptech.glide.ksp
    implementation(libs.smehranb.glowbutton)

    testImplementation libs.junit.jupiter.api
    testRuntimeOnly libs.junit.jupiter.engine
    testImplementation libs.junit.jupiter.params
    testRuntimeOnly libs.junit.platform.launcher

    testImplementation libs.hamcrest

    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
    androidTestImplementation libs.androidx.test.espresso.intents
}
